/**
 * Placeholder data for UI design only — not connected to the database yet.
 * Delete this file once GET /api/admin/locations exists and LocationsPanel
 * fetches real rows from the `locations` table instead.
 */
export const SAMPLE_LOCATIONS = [
  {
    id: 1,
    locationName: 'Molo Plaza Terminal',
    locationType: 'terminal',
    address: 'Molo District, Iloilo City',
    latitude: '10.6975',
    longitude: '122.5406',
    description: 'Main jeepney terminal serving Molo–Jaro routes.',
    createdBy: 'System Admin',
    createdAt: '2026-06-01 09:12 AM',
  },
  {
    id: 2,
    locationName: 'SM City Iloilo Terminal',
    locationType: 'terminal',
    address: 'Mandurriao, Iloilo City',
    latitude: '10.7181',
    longitude: '122.5622',
    description: 'Terminal beside the mall entrance.',
    createdBy: 'System Admin',
    createdAt: '2026-06-01 09:20 AM',
  },
  {
    id: 3,
    locationName: 'Jaro Plaza Waiting Shed',
    locationType: 'waiting_area',
    address: 'Jaro, Iloilo City',
    latitude: '10.7237',
    longitude: '122.5644',
    description: 'Covered waiting area near the belfry.',
    createdBy: 'System Admin',
    createdAt: '2026-06-02 08:05 AM',
  },
  {
    id: 4,
    locationName: 'Robinsons Place Iloilo',
    locationType: 'stop',
    address: 'Iloilo–Jaro Rd, Iloilo City',
    latitude: '10.7143',
    longitude: '122.5590',
    description: '',
    createdBy: 'System Admin',
    createdAt: '2026-06-02 10:41 AM',
  },
  {
    id: 5,
    locationName: 'Iloilo Provincial Capitol',
    locationType: 'landmark',
    address: 'Bonifacio Dr, Iloilo City',
    latitude: '10.6963',
    longitude: '122.5644',
    description: 'Common reference point for directions downtown.',
    createdBy: 'System Admin',
    createdAt: '2026-06-03 01:15 PM',
  },
  {
    id: 6,
    locationName: 'La Paz Public Market',
    locationType: 'terminal',
    address: 'La Paz, Iloilo City',
    latitude: '10.7304',
    longitude: '122.5507',
    description: 'Jeepney and tricycle terminal beside the market.',
    createdBy: 'System Admin',
    createdAt: '2026-06-03 03:30 PM',
  },
  {
    id: 7,
    locationName: 'Iloilo River Esplanade',
    locationType: 'landmark',
    address: 'Diversion Rd, Iloilo City',
    latitude: '10.6899',
    longitude: '122.5738',
    description: 'Popular drop-off point near the riverwalk.',
    createdBy: 'System Admin',
    createdAt: '2026-06-04 07:50 AM',
  },
]